### ISSUE TITLE
Index inaccessible if using #input instead of #each input syntax? Issue with nested each

### ISSUE THREAD

**Issue by aweintraut** [Handlebars-Net/Handlebars.Net#122]
My "Input" in this example is a list of a class called A (as returned by BuildTestData).  Is there a way to access the index when using the alternate #Input syntax?

``` csharp
        [Theory]
        [InlineData("{{#each Input}}ii={{@index}} {{/each}}")] //Succeeds
        [InlineData("{{#Input}}ii={{@index}} {{/Input}}")] //Fails
        public void TestSingleLoopDictionary(string source)
        {
            var template = Handlebars.Compile(source);
            var data = new
            {
                Input = BuildTestData()
            };
            var result = template(data);
            Debug.WriteLine($"Source: {source}");
            Debug.WriteLine($"Result: {result}");
            Assert.Equal("ii=0 ii=1 ii=2 ", result);
        }
```

**Comment by rexm** [comment]
Currently, you will only get context variables (like @index) if you use one of the built-in enumerators. The implicit block handler (#myThing) waits until the last possible moment to determine what the actual value of myThing is, and then applies a very simplistic binding that doesn't create a child iterator context.

Not to say that can't be done in a future version, but not currently supported. PR always welcome!

**Comment by aweintraut** [comment]
I've simplified this example because I wanted to test what was going wrong in a particular situation.  I have unit tests that show that given a hierarchical structure, class A has list of B has dictionary of C has list of D...that I can do something like the following (which passes as long as I don't try to use index with #Listname syntax):

```csharp
        [Theory]
        [InlineData(
            "<Input>{{#each Input}}<A Name={{AName}}>{{#each BList}}<B Name={{BName}}>{{#each CDict}}<C Name={{CName}} Index={{@index}}>{{#each DList}}<D Name={{DName}}/>{{/each}}</C>{{/each}}</B>{{/each}}</A>{{/each}}</Input>"
            )]
        [InlineData(
            "<Input>{{#Input}}<A Name={{AName}}>{{#BList}}<B Name={{BName}}>{{#each CDict}}<C Name={{CName}} Index={{@index}}>{{#DList}}<D Name={{DName}}/>{{/DList}}</C>{{/each}}</B>{{/BList}}</A>{{/Input}}</Input>"
            )]
        //ERR Unable to access index when using #Cdict syntax[InlineData("<Input>{{#Input}}<A Name={{AName}}>{{#BList}}<B Name={{BName}}>{{#CDict}}<C Name={{Value.CName}} Index={{@index}}>{{#Value.DList}}<D Name={{DName}}/>{{/Value.DList}}</C>{{/CDict}}</B>{{/BList}}</A>{{/Input}}</Input>")]
        public void AccessIndexWithdictionary(string source)
        {
            var template = Handlebars.Compile(source);
            var data = new
            {
                Input = BuildTestData()
            };
            var result = template(data);
            Debug.WriteLine($"Source: {source}");
            Debug.WriteLine($"Result: {result}");
            Assert.Equal(
                "<Input><A Name=A1Name><B Name=A1B1Name><C Name=A1B1C1Name Index=0><D Name=C1D1Name/><D Name=C1D2Name/></C><C Name=A1B1C2Name Index=1><D Name=C2D1Name/><D Name=C2D2Name/></C><C Name=A1B1C3Name Index=2><D Name=C3D1Name/><D Name=C3D2Name/></C></B><B Name=A1B2Name><C Name=A1B2C1Name Index=0></C><C Name=A1B2C2Name Index=1></C><C Name=A1B2C3Name Index=2></C></B></A><A Name=A2Name><B Name=A2B1Name><C Name=A2B1C1Name Index=0></C><C Name=A2B1C2Name Index=1></C><C Name=A2B1C3Name Index=2></C></B><B Name=A2B2Name><C Name=A2B2C1Name Index=0></C><C Name=A2B2C2Name Index=1></C><C Name=A2B2C3Name Index=2></C></B></A><A Name=A3Name><B Name=A3B1Name><C Name=A3B1C1Name Index=0></C><C Name=A3B1C2Name Index=1></C><C Name=A3B1C3Name Index=2></C></B><B Name=A3B2Name><C Name=A3B2C1Name Index=0></C><C Name=A3B2C2Name Index=1></C><C Name=A3B2C3Name Index=2></C></B></A></Input>",
                result);
        }

```

However in my actual usage example, I'm getting a different result.  I'm not able to use the "each" syntax in a nested loop, the inner loop does not seem to execute.  As an example I output the same content three ways.  You can see the watch window results.  Perhaps it would be best at this point to get your source and debug in, but I thought I would check on the @index capability (hoping perhaps I just hadn't identified the correct syntax) since the #A #B /B /A syntax is the one producing the expected results:

```csharp
Handlebars.Compile("BOTHEACH- {{#each Samples}} Sample : {{#each SampleDetails}} sdIndex= {{@index}}{{/each}}{{/each}}  INNEREACH-{{#Samples}} Sample : {{#each SampleDetails}}sdIndex={{@index}} {{/each}} {{/Samples}}  NOEACH- {{#Samples}} Sample : {{#SampleDetails}} sdIndex={{@index}} {{/SampleDetails}} {{/Samples}}")(input)
```

If you look at the output from the watch below, there is clearly some issue using nested eaches preventing the inner loop from executing?  Samples is a list and SampleDetails is a dictionary in this example, but that executed fine in the unit test example:

BOTHEACH-  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :  Sample :   INNEREACH- Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :   Sample :    NOEACH-  Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=   Sample :  sdIndex=  sdIndex=  sdIndex=  sdIndex=  sdIndex=
