### ISSUE TITLE
Decorators implementation

### ISSUE THREAD

**Issue by sandorfr** [Handlebars-Net/Handlebars.Net#137]
Decoratos are the latest addition to handlebarsjs. It seems it is not yet ported. Do you have any plans about it?

**Comment by rexm** [comment]
I haven't given decorators any thought yet. PR welcome as always

**Comment by rexm** [comment]
On the [2.0 roadmap](https://github.com/rexm/Handlebars.Net/issues/294).

**Comment by zjklee** [comment]
Issues https://github.com/Handlebars-Net/Handlebars.Net/issues/306, https://github.com/Handlebars-Net/Handlebars.Net/issues/380 and https://github.com/Handlebars-Net/Handlebars.Net/issues/300 depend on this feature
