### ISSUE TITLE
using dot as literal does not work

### ISSUE THREAD

**Issue by fikkatra** [Handlebars-Net/Handlebars.Net#158]
Compiling a template which includes dots as a literal (using the literal syntax [ ]) does not seem to work.
Template: `<h1>{{[a.literal]}}</h1>`
Data:`{ "a.literal": "My Text" }`

Output: `<h1></h1>`

I tried this out using http://tryhandlebarsjs.com/ and it works as expected (output is `<h1>My Text</h1>`)

Might have something to do with [this ](https://github.com/jknack/handlebars.java/issues/311) issue on the handlebars.java github (although that's for Java)

**Comment by rexm** [comment]
I don't believe the literal syntax is entirely supported yet.
