### ISSUE TITLE
Question : how to define an array as argument (when using a custom helper)

### ISSUE THREAD

**Issue by StefH** [Handlebars-Net/Handlebars.Net#273]
Let's assume I've defined a custom helper named `Random` , and I want to provide a list of strings to this helper arguments.

Example:
``` c#
var template = Handlebars.Compile("{{Random Values=['a', 'b', 'c'] }}");
```
This does not work because `Values` is an `UndefinedBindingResult`.

How to provide an array ?

**Comment by zjklee** [comment]
Do not think it's possible at the moment. Parser knows nothing about `[]` array notation.
As an alternative the following can be used:
```csharp
var template = Handlebars.Compile("{{Random 'a' 'b' 'c' }}");
```

**Comment by StefH** [comment]
Hello @zjklee,

I think already found a way to implement this (I'm using json...):
- https://github.com/StefH/Handlebars.Net.Helpers/blob/master/src/Handlebars.Net.Helpers/Parsers/ArgumentsParser.cs#L42
- https://github.com/StefH/Handlebars.Net.Helpers/blob/master/src/Handlebars.Net.Helpers/Utils/ArrayUtils.cs#L15

Demo see:
https://stefh.github.io/BlazorAppHandlebarsDemo/
![image](https://user-images.githubusercontent.com/249938/96220456-0bedc480-0f89-11eb-95b2-05fd9e757c48.png)
