### ISSUE TITLE
Can't seem to handle German umlauts....

### ISSUE THREAD

**Issue by marcscheuner-bfh** [Handlebars-Net/Handlebars.Net#276]
I have a template that shows German first and last names - something like

`{{firstname}} {{lastname}}`

If I provide a name like firstname="Peter", lastname="Müller", I get this in my result string:

`Peter M&#252;ller`

Is there any way in Handlebars.NET to **AVOID** this encoding? I just want the normal text "Peter Müller" back, since I need this inside an e-mail template.......

**Comment by rexm** [comment]
Generally e-mail clients handle encoded characters better than the expanded character sets. It is possible to introduce your own encoder that doesn't do this, on the Configuration object, but I'd wonder why for e-mail.

**Comment by tonysneed** [comment]
This is an [issue](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/issues/30) for my Handlebars scaffolding for EF Core, which in general should suppress HTML encoding.

I noticed that `EncodedTextWriter` has a `SuppressEncoding` property.  Would it be possible to add this property to `HandlebarsConfiguration`, so that HTML encoding could be suppressed?

**Comment by tonysneed** [comment]
@rexm If you point me in the right direction, I can submit a PR for this.

**Comment by rexm** [comment]
HandlebarsJS has a configuration option `noEscape` that disables all encoding. I think a `NoEscape` boolean on configuration that controls/overrides the EncodedTextWriter would be appropriate.

**Comment by marcscheuner-bfh** [comment]
@rexm : yes, sounds very reasonable and would increase the usefulness of Handlebars.NET - you definitely got my vote on this one!

**Comment by tonysneed** [comment]
👍 For adding this fix to the next version of Handlebars.NET.

**Comment by tonysneed** [comment]
Is there now a NoEscape boolean on configuration?

**Comment by zjklee** [comment]
Yes, it is available in latest master. Unfortunately it is not yet published.
