### ISSUE TITLE
Layout overriding block with inline

### ISSUE THREAD

**Issue by fhogberg** [Handlebars-Net/Handlebars.Net#300]
Tried using a layout inheritance and defining blocks inline.
Am i doing something wrong or is this currently not supported?
```csharp      
        public void PartialLayoutAndInlineBlock()
        {
            string layout = "{{#>body}}{{fallback}}{{/body}}";
            string page = @"{{#>layout}}{{#*inline ""body""}}{{truebody}}{{/inline}}{{/body}}{{/layout}}";


            var template = Handlebars.Compile(page);

            var data = new
            {
                fallback = "aaa",
                truebody = "Hello world"
            };

            using (var reader = new StringReader(layout))
            {
                var partialTemplate = Handlebars.Compile(reader);
                Handlebars.RegisterTemplate("layout", partialTemplate);
            }
            var result = template(data);
            Assert.Equal("Hello world", result);
        }

**Comment by olegolo** [comment]
Any progress on this?

**Comment by zjklee** [comment]
Hello @olegolo .
Unfortunately resources of supporters are limited and we're not capable of handling all the issues simultaneously. The main priority for now is 2.0 release.
If this is critical functionality for you I'd kindly ask to help with the investigation and fixing.

**Comment by olegolo** [comment]
Problem statement:
Having a layout
`Handlebars.RegisterTemplate("layout", @"Hello {{>sec1}}" and {{>sec2}}");`
and a template
`{{#*inline 'sec1'}} Tom {{/inline}}
 {{#*inline 'sec2'}} Jerry {{/inline}}`

Expected result: Hello Tom and Jerry
Actual result: Hello and Jerry

After some experiments, I found out that the first section is always used for the 'everything else' like the texts outside of sections.

Workaround#1 inverse dependencies and register template as partial

Workaround#2 having a layout with the first Default section
`{{#*inline 'garbage'}} this is going to fall into hidden div for example {{/inline}}
{{#*inline 'sec1'}} Tom {{/inline}}
 {{#*inline 'sec2'}} Jerry {{/inline}}`

Suggestion
Add the ability to completely disable garbage content and omit the first (mandatory to make it work) section.

**Comment by zjklee** [comment]
Possibly related issue: Handlebars-Net/Handlebars.Net/issues/300

**Comment by zjklee** [comment]
Had a quick look at the issue.
The problem is related to the order we execute `*inline`. `*inline` has decorator behaviour and should be executed as the first statement on the block. Unfortunately right now it's not handled in this way.
