### ISSUE TITLE
RuntimeBinder Memory leaks

### ISSUE THREAD

**Issue by DmitryDem** [Handlebars-Net/Handlebars.Net#308]
Method GetProperty(object target, string name) in the PathBinder.cs  and IteratorBinder.cs cause memory leak in highload application. Could you use another way for getting property value instead of using RuntimeBuilder class?
![image](https://user-images.githubusercontent.com/5823289/62298546-b6e89000-b462-11e9-8d2b-19c933dfef49.png)

**Comment by rexm** [comment]
PR welcome

**Comment by DmitryDem** [comment]
Hi!
Maybe we can use ExpressionTrees instead RuntimeBuilder?

For example:
var parameter = Expression.Parameter(typeof(object));
 var cast = Expression.Convert(parameter, value.GetType());
 var propertyGetter = Expression.Property(cast, propertyName);
 var castResult = Expression.Convert(propertyGetter, typeof(object));//for boxing
 var propertyRetriver = Expression.Lambda<Func<object, object>>(castResult, parameter).Compile();
  var retrivedPropertyValue = propertyRetriver(value);

I know that's not a cheap operation because expression threes should be compiled. But i think that's it should be faster then DLR. What do you think?

**Comment by rexm** [comment]
Inside of the Binders, this is specific to objects that implement
IDynamicMetaObjectProvider
... so taking the time to see how the CLR deals with that interface and
using that as a starting point would be a good approach.

**Comment by DmitryDem** [comment]
Yea, sorry, didn't notice

**Comment by DmitryDem** [comment]
What do you think about CallSite caching?  I think it's should help. The main problem occurs when creating CallSite objects.
For example:
internal static class CallSiteCache
    {
        private static readonly ConcurrentDictionary<string, CallSite<Func<CallSite, object, object>>> getters = new ConcurrentDictionary<string, CallSite<Func<CallSite, object, object>>>();

        internal static object GetValue(object target, string name)
        {
            var callSite = getters.GetOrAdd(name, CreateSite(target, name));
            return callSite.Target(callSite, target);
        }

        internal static CallSite<Func<CallSite, object, object>> CreateSite(object target, string name)
        {
            return CallSite<Func<CallSite, object, object>>.Create(Binder.GetMember(CSharpBinderFlags.None, name, target.GetType(), new[] { CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.None, null) }));
        }
    }

**Comment by rexm** [comment]
Looking at this: https://docs.microsoft.com/en-us/dotnet/api/system.dynamic.dynamicmetaobject.bindgetmember?view=netframework-4.8#System_Dynamic_DynamicMetaObject_BindGetMember_System_Dynamic_GetMemberBinder_

**Comment by DmitryDem** [comment]
I don't understand how this api can help. Usually this api uses for custom DynamicObject implementation and contains describing get methods of custom DynamicObject. Could you please clarify idea for using this api.

**Comment by DmitryDem** [comment]
I have just implemented some solution. What do you think?
```
 private static object GetProperty(IDynamicMetaObjectProvider target, string name)
        {
            var self = (Expression)Expression.Constant(target);
            var metaObject = target.GetMetaObject(self);
            var binder = (GetMemberBinder)Binder.GetMember(CSharpBinderFlags.None, name, target.GetType(), new[] { CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.None, null) });
            var member = metaObject.BindGetMember(binder);
            BlockExpression final = Expression.Block(
                Expression.Label(CallSiteBinder.UpdateLabel),
                member.Expression
            );
            var param = Expression.Parameter(typeof(object));
            var lambda = Expression.Lambda(final, param);
            var @delegate = lambda.Compile();
            return @delegate.DynamicInvoke(target);
        }
```

**Comment by rexm** [comment]
That all makes sense to me except I don’t entirely understand the Lambda wrapper bit - can you explain?

**Comment by DmitryDem** [comment]
Yes lambda wrapper could be simplified. I think we could replace Lambda wrapper with this
```
var lambda = Expression.Lambda<Func<object>>(final).Compile();
            return lambda();
```
These lines do not make sense.
```
 var param = Expression.Parameter(typeof(object));
            var lambda = Expression.Lambda(final, param);
```

**Comment by rexm** [comment]
The `DynamicMetaObject` has other properties that look like they give direct access to the underlying value without creating a new expression tree - take a look at the Properties section on https://docs.microsoft.com/en-us/dotnet/api/system.dynamic.dynamicmetaobject?view=netframework-4.8

**Comment by DmitryDem** [comment]
Do you mean "Value" property?  It does't work for ExpandoObject. It just return null.
![image](https://user-images.githubusercontent.com/5823289/62377497-6476a480-b532-11e9-84f0-5d316115f9a0.png)
Instead of we can call Expression that contains logic access to the member
![image](https://user-images.githubusercontent.com/5823289/62377647-b4ee0200-b532-11e9-874d-e7d92d40d4ea.png)
Every custom DynamicMetaObject that inherited from DynamicMetaObject  can override BindGetMember and provide Expression for access to their members.
Look at example for JObject from Json.NET library
![image](https://user-images.githubusercontent.com/5823289/62378234-e87d5c00-b533-11e9-83d1-1cf888df98e9.png)
If you know another way I will be grateful for the help

**Comment by rexm** [comment]
`ExpandoObject` implements `IDictionary<string,object>` so may want to consider reordering the type checks to give that precedence. The structure of the routine should be that if a value isn't resolvable after one attempt, fall back up and keep trying others.

**Comment by XcoderBlood** [comment]
Was this ever fixed?
