### ISSUE TITLE
Way to access complete data object from helper

### ISSUE THREAD

**Issue by huysentruitw** [Handlebars-Net/Handlebars.Net#320]
I'm trying to get a translation helper working and I'm pretty close:

In the template, I'm writing:

    {{ translate "Hello world" }}

Then I have a helper:

```csharp
_handlebars.RegisterHelper("translate", new HandlebarsHelper((writer, data, obj) =>
{
    if (obj.Length != 1 || !(obj[0] is string caption))
        return;

    if (data is HandlebarsCultureSpecificTemplateData tempateData)
    {
        caption = tempateData.Translate?.Invoke(caption) ?? caption;
    }

    writer.Write(caption);
}));
```

The class looks like this:

```
internal class HandlebarsCultureSpecificTemplateData
{
    public Func<string, string> Translate { get; set; }
    public CultureInfo Culture { get; set; }
}
```

Now, this works, until I get into an `{{#each}}` loop, there `data` in the helper no longer points to the root object, but points to the current element of the 'each'.

So, my question: how to access the root object from the helper (in all cases) OR how can I execute the helper from the template, but making sure it's getting called from the root scope? (like `@root`)

**Comment by huysentruitw** [comment]
Currently changed our usage to: `{{ translate @root "Hello world" }}`

And helper to:

```csharp

_handlebars.RegisterHelper("translate", new HandlebarsHelper((writer, data, obj) =>
{
    if (obj.Length != 2 || !(obj[1] is string caption))
        return;

    if (obj[0] is HandlebarsCultureSpecificTemplateData tempateData)
    {
        caption = tempateData.Translate?.Invoke(caption) ?? caption;
    }

    writer.Write(caption);
}));
```

A cleaner way would be nice :)

**Comment by rexm** [comment]
How does it work in handlebars js?

**Comment by huysentruitw** [comment]
In handlebars js, they're passing the `options` instance to the helper callback, where `options.data` contains the raw data that is being feeded to the compile function.

**Comment by rexm** [comment]
@huysentruitw To make sure we've got the use case nailed down, can you please share a simple example template & helper written in handlebars js, with an example JSON model?
