### ISSUE TITLE
Extend the handlers with an direct access to @root over their parameters

### ISSUE THREAD

**Issue by GitHub-TC** [Handlebars-Net/Handlebars.Net#322]
- public delegate void HandlebarsHelper     (TextWriter output, object root, dynamic context, params object[] arguments);
- public delegate void HandlebarsBlockHelper(TextWriter output, object root, HelperOptions options, dynamic context, params object[] arguments);

I used this to access the main data structure from the calling in the handler functions. Before this, the data structure have to be "public static" or the scripts must have an weird @root parameter.

**Comment by rexm** [comment]
Not clear to me what you’re asking, can you elaborate?

**Comment by GitHub-TC** [comment]
I needed handlers that have access to the calling data structure to access the context of the entire execution.

My first approach was that the handler always had to be given a @root parameter that had to be entered in the HBS scripts.
E.G. {{fontsize @root 6}}
because the fontsize referred to the instance. However, this makes little sense from the point of view of the script, which is why I prefer a {{fontsize 6}}. This is with my change also possible because EVERY handler has direct access to the @root instance and thus the scripts are freed of unnecessary payload.

Here's my fork:
https://github.com/GitHub-TC/Handlebars.Net

and i used this in the
https://github.com/GitHub-TC/EmpyrionScripting

**Comment by rexm** [comment]
Handlebarsjs doesn't support this today - helpers are limited to the data scope they have access to.

**Comment by GitHub-TC** [comment]
I know that, and I changed my (fork) version to do that.
My question is if you are interested in this change?

**Comment by rexm** [comment]
Willing to consider it for v2, but want to put a little more thought into how to achieve it with closer alignment to how the JS library logically works.

**Comment by brechtvhb** [comment]
Is it already possible to access the root context from a helper without having to inject @root?

**Comment by GitHub-TC** [comment]
@brechtvhb Unfortunately not, I once wanted this a long time ago but then had to do it myself in a fork. https://github.com/GitHub-TC/Handlebars.Net
So that it is not a breaking change, you would have to support both handler types, which is of course more work.
