### ISSUE TITLE
[Suggestion] Fallback to instance/static method if helper cannot be resolved

### ISSUE THREAD

**Issue by zjklee** [Handlebars-Net/Handlebars.Net#336]
## Problem
Sometimes it's required to use some well-known methods inside of the template (like `string.ToUpper()`) and in order to do so you need to register new helper for each of such occurrences.

## Solution
Right now there are two stages for helper binding: 
- compile time: helper is registered before template is compiled
- late bind: helper is registered after template is compiled

I propose to add a third step, controlled by feature toggle in settings, that would try to resolve and invoke:
- instance method of the object
- static method of the type (if instance method was not found)

Adding the feature toggle is essential for a few reasons:
- potential unexpected behavior due to lack of support in Handlebarsjs (see section below)
- potential performance degradation (may be resolved by adding `Compile<ExpectedModelType>()` mentioned in #294 )

## Support in Handlebarsjs
There was a discussion (wycats/handlebars.js/issues/168) regarding this functionality. The proposal was rejected. However for JS there's [workaround](https://github.com/wycats/handlebars.js/issues/168#issuecomment-3937752) mentioned in the same thread - you can override the handler. Unfortunately such overrides are not available in current implementation mostly because of .NET nature. 

## Useful for
The functionality may be useful for people who does not have strong performance requirements but require more feature reach and flexible templating engine. One of the examples may be generation of deployment artifacts (e.g. [`ARM` template parameters](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/parameter-files) generation).

**Comment by crackalak** [comment]
@zjklee what feature toggle did you add this under in your fork?

**Comment by rexm** [comment]
Can you start a PR?

**Comment by zjklee** [comment]
> @zjklee what feature toggle did you add this under in your fork?

@crackalak instead of hiding hard-coded resolved behind feature toggle I've exposed an extension point [`IHelperResolver`](https://github.com/zjklee/Handlebars.CSharp/blob/master/source/Handlebars/Configuration/HandlebarsConfiguration.cs#L37). For an example please see [CustomHelperResolverTest](https://github.com/zjklee/Handlebars.CSharp/blob/master/source/Handlebars.Test/BasicIntegrationTests.cs#L1767)

> Can you start a PR?

@rexm Sure. Unfortunately due to the nature and amount of changes I'd not be able to extract this particular change out from the whole scope - the PR would be "all or nothing". You can look at zjklee/Handlebars.CSharp/pull/3 to see the scope.
