### ISSUE TITLE
Context passed to helpers

### ISSUE THREAD

**Issue by fhogberg** [Handlebars-Net/Handlebars.Net#339]
Since a lot of code for .net is based around viewcontexts it would be great to be able to pass a viewcontext to a template so that i can get a reference to it from helpers.
The function could be that any data passed to render would be accessable to helpers as a sort of state object.
Since templates compile to a Func<string,object> no passing of other things then.
Don't think this is possible now. Am i wrong?
Would it be regarded as in scope for this project?
Would you accept a pull request for it?

**Comment by zjklee** [comment]
Looks related to Handlebars-Net/Handlebars.Net/issues/368
