### ISSUE TITLE
does not compile correctly #if

### ISSUE THREAD

**Issue by jairandresdiazp** [Handlebars-Net/Handlebars.Net#340]
does not compile correctly the #if always deviates to the false condition

Version nuget: 1.10.1

template

{{#if Email}}
"correo": "{{Email}}",
{{else}}
"correo": "no hay correo",
{{/if}}

data

{
    "Email": "correo@gmail.com",
    "DocumentNumber": "79696560",
    "ParentEntityId": 10
}

result

"correo": "no hay correo",

**Comment by vandert** [comment]
I'm having a similar issue.  Here's my template:
`<doc>
  <h1>Heading 1</h1>
  <section>
    <text>{{ name }}</text><br/>
    <text>{{ age }}</text>
    {{#if email}}
    <br/>
    <text>{{email}}</text>
    {{/if}}
  </section>
</doc>`

And my data:
`{
  "name":"Van",
  "age":49,
  "email": "vthompson@example.com"
}`

And the rendered result:
`...
! U1 SETLP 4 0 47
Heading 1
! U1 SETLP 7 0 24
Van
49

! U1 END-PAGE`

I'm expecting the email address to display below the number 49

**Comment by vandert** [comment]
I resolved my issue.  Originally I was converting JSON to a Json.NET JObject.  I changed this to an ExpandoObject as done in the Json tests.

**Comment by moialbla** [comment]
> I resolved my issue. Originally I was converting JSON to a Json.NET JObject. I changed this to an ExpandoObject as done in the Json tests.

Thank you!, your solution works fine. Anyway , The library will solve this "bug"?
Best,

**Comment by winzig** [comment]
In my case I cannot convert to ExpandoObject. Is there any plan to fix the underlying issue?

**Comment by winzig** [comment]
I found a workaround, creating a block helper I call `ifdef` which basically does what I would have expected `if` to do.

```csharp
HandlebarsBlockHelper _ifDefinedBlockHelper = (System.IO.TextWriter output, HelperOptions options, dynamic context, object[] arguments) => 
{   
    string arg = arguments[0].ToString();

    if (!string.IsNullOrEmpty(arg))
    {
        options.Template(output, context);
    }
    else
    {
        options.Inverse(output, context);
    }
};

Handlebars.RegisterHelper("ifdef", _ifDefinedBlockHelper);
```

Then I use it like this with a JObject and it works fine.

```
{{ifdef MyVar}} - {{MyVar}}{{/ifdef}}
```

The example above shows how to use it to print a separator hyphen only when `MyVar` has a value.

**Comment by zjklee** [comment]
> In my case I cannot convert to ExpandoObject. Is there any plan to fix the underlying issue?

Hello @winzig , yes, this one is going to be addressed. However the fix would be provided as an external NuGet package that would add proper support for Json.Net and System.Text.Json. Unfortunately release date is unknown.

**Comment by jairandresdiazp** [comment]
Register your own function to achieve what you want, at the moment it is the only option available


`Handlebars.RegisterHelper("exist", (writer, option, context, parameters) =>
{
	if (parameters.Length != 1)
	{
		writer.Write("{{exist}} must have exactly 1 argument\"\"");
	}
	if (HandlebarsUtils.IsUndefinedBindingResult(parameters[0]))
		option.Inverse(writer, (object)context);
	if (((JValue)parameters[0]).Type == JTokenType.Null)
		option.Inverse(writer, (object)context);
	if (((JValue)parameters[0]).Type == JTokenType.Boolean)
		if (bool.Parse(parameters[0].ToString()))
			option.Template(writer, (object)context);
		else option.Inverse(writer, (object)context);
	else if (((JValue)parameters[0]).Type == JTokenType.String)
		if (parameters[0].ToString() != "")
			option.Template(writer, (object)context);
		else option.Inverse(writer, (object)context);
	else if (((JValue)parameters[0]).Type == JTokenType.Array)
		if (parameters[0].ToString() != "")
			option.Template(writer, (object)context);
		else option.Inverse(writer, (object)context);
	else
		option.Template(writer, (object)context);
});`

use it in your template like this

`{{#exist input}}
value input exist
{{else}}
value input not exist
{{/exist}}`

**Comment by zjklee** [comment]
See [Handlebars.Net.Extension.NewtonsoftJson](https://github.com/Handlebars-Net/Handlebars.Net.Extension.NewtonsoftJson).
