### ISSUE TITLE
Question : is there also a .NET helper library as defined by javascript?

### ISSUE THREAD

**Issue by StefH** [Handlebars-Net/Handlebars.Net#343]
See:
https://github.com/helpers/handlebars-helpers

**Comment by StefH** [comment]
@rexm 
I can start building some string helper methods and put this in a new NuGet/project like `Handlebars.Net.Extensions` or `Handlebars.Net.Helpers`.

It would be useful to add the source code to this project and that you add me as team member on this project (if you like).

What do you think?

**Comment by rexm** [comment]
That’s a great idea! Will follow up this evening.

**Comment by StefH** [comment]
Started a new project : https://github.com/StefH/Handlebars.Net.Helpers/tree/master/Handlebars.Net.Helpers

Just have a look...

**Comment by StefH** [comment]
@rexm 
1. did you have time to look?
2. when do you plan to release a NuGet from the current project ? I'm waiting on this https://github.com/rexm/Handlebars.Net/issues/298

**Comment by nzjoel1234** [comment]
Thanks @StefH  for the helpers. Your link doesn't work but this does: https://github.com/StefH/Handlebars.Net.Helpers

**Comment by StefH** [comment]
@nzjoel1234  Thanks. If you have any comments, questions, just create an issue on my project.

**Comment by zjklee** [comment]
See [Handlebars.Net.Helpers](https://github.com/Handlebars-Net/Handlebars.Net.Helpers).
