### ISSUE TITLE
Specifiy CultureInfo ?

### ISSUE THREAD

**Issue by StefH** [Handlebars-Net/Handlebars.Net#344]
It seems that the **writer** used in:
``` c#
handlebarsContext.RegisterHelper(name, (writer, context, arguments) =>
// and
handlebarsContext.RegisterHelper(name, (writer, options, context, arguments) =>
```

Is always using the current culture ? Is there a way to change this?

**Comment by zjklee** [comment]
You can try to use `Action<TextWriter, object> Compile(TextReader template)` overload and pass `TextWriter` with configured `IFormatProvider`. 
Passed `TextWriter` should then be used in helpers.

**Comment by StefH** [comment]
@zjklee Thanks for your idea.

At this moment, I solved this by adding extensions method to `TextWriter`, see this code:
https://github.com/StefH/Handlebars.Net.Helpers/blob/master/src/Handlebars.Net.Helpers/Extensions/TextWriterExtensions.cs
