### ISSUE TITLE
Can custom helper return object?

### ISSUE THREAD

**Issue by hsamhita** [Handlebars-Net/Handlebars.Net#347]
"{{someParentContextField}}
{{#with helperWhichReturnsObject}}
{{fieldFromHelperReturnedObject}}
{{/with}}"

Wondering if above is feasible. Any help is appreciated.

**Comment by zjklee** [comment]
Unfortunately in current version it's not possible.
I've implemented such functionality in my fork [zjklee/Handlebars.CSharp](https://github.com/zjklee/Handlebars.CSharp) and currently working on back-porting the changes. For the whole list of changes please see [zjklee/Handlebars.CSharp/pull/3](https://github.com/zjklee/Handlebars.CSharp/pull/3)
The correct template should look like this:
```handlebars
{{#with (helperWhichReturnsObject)}}
  {{fieldFromHelperReturnedObject}}
{{/with}}
```
The only difference is that you need to call the helper with return value as a sub-expression.

**Comment by deepak-ms** [comment]
Thanks zjklee for the information!

**Comment by hsamhita** [comment]
Thanks zjklee for the information!
