### ISSUE TITLE
HandlebarsUndefinedBinding thrown for null ExpandoObject values

### ISSUE THREAD

**Issue by andycnguyen** [Handlebars-Net/Handlebars.Net#351]
I've been trying to convert my Handlebars models to ExpandoObjects, as recommended in various issues here. However, I've found that that a `HandlebarsUndefinedBinding` exception is thrown for `null` values.

For example, I'd like to make use of templates and models like the following:

```
{{#if PerhapsNull}}
     It's not null
{{else}}
     It's null
{{/if}}
```
```
dynamic data = new ExpandoObject();
data.PerhapsNull = null;
```
This doesn't work, however, due to the aforementioned exception. I'm aware that I could suppress this exception by setting `ThrowOnUnresolvedBindingExpression = false`, but I'd rather not do this. (And it seems to me that, in the example I've given, the expression in question should not be considered unresolved.)

**Comment by zjklee** [comment]
I've tested you problem on my fork [zjklee/Handlebars.CSharp](https://github.com/zjklee/Handlebars.CSharp) and it works.
You can try using it until changes are merged to the main repo.
