### ISSUE TITLE
A false result of a boolean helper is interpreted as a truthy "false" string

### ISSUE THREAD

**Issue by sferencik** [Handlebars-Net/Handlebars.Net#361]
A false result of a boolean helper is interpreted as a truthy `"False"` string.

Test case:
```
{{#if (Regex.IsMatch "a" "b")}}
 TRUE
{{else}}
 FALSE
{{/if}}
```
This prints TRUE; we should expect FALSE.

(`Regex.IsMatch` taken from https://github.com/StefH/Handlebars.Net.Helpers/wiki/Regex#ismatch .)

`IsMatch` correctly evaluates the regex match as `(bool) False` and prints it to the text writer. Then the sub-expression handler pulls it out as the `"False"` string and hands it over to the built-in "#if". The "#if" expects a boolean value so it runs `HandlebarsUtils.IsTruthyOrNonEmpty("False")` which evaluates it as `true`.

I believe `"False"` should evaluate to `false`, especially if produced by a `boolean` expression. The user shouldn't be affected by the fact that Handlebars.Net converts the value to string first (and pulls it out using `CaptureTextWriterOutputFromHelper()`).

For comparison, this works fine in JS:
```
handlebars.registerHelper('soBoolean', () => false);
const boolTemplate = handlebars.compile('{{#if (soBoolean)}}TRUE{{else}}FALSE{{/if}}');
console.log(boolTemplate()); // TRUE
```

The easy fix is to change `IsFalsy()` to perform `Boolean.TryParse()` for string values.

We might also want to consider [my earlier suggestion](https://github.com/Handlebars-Net/Handlebars.Net/issues/294#issuecomment-636197037) that helpers should return value rather than print it to the text writer.

**Comment by zjklee** [comment]
@sferencik 
> We might also want to consider my earlier suggestion that helpers should return value rather than print it to the text writer

The support for value returns is going to be added by Handlebars-Net/Handlebars.Net/pull/359

**Comment by sferencik** [comment]
Wonderful, I see it now. Thanks for that.

This, sadly, won't directly help my case because HandlebarsHelpers.Net will still be registering the helpers (incl. `Regex.IsMatch`) the old way, as writers rather than returners. So I think we should still discuss how to roll this out globally, e.g. as a backward-incompatible change with 2.0 (see #294), making all helpers return rather than write. Then, anyone upgrading to Handlebars.Net 2.0 would need to fix up their helpers perhaps.

**Comment by zjklee** [comment]
When I was working on returning helpers I also thought on deprecating 'write'-helpers. However I've came to a conclusion that this is not the best way to go.
Better way is to update Helpers library itself. @StefH would you be able to do the change once v2 is published?

**Comment by sferencik** [comment]
Or even as soon as the returning helpers (your current PR) are released,
right? (IIUC, 2.0 is still a long way out, right?)

**Comment by StefH** [comment]
@zjklee and @sferencik 

I can update the https://github.com/StefH/Handlebars.Net.Helpers project once this project has version 2.0

(Note: my helper library can also be used by https://github.com/zjklee/Handlebars.CSharp) what do we do there?

**Comment by zjklee** [comment]
@StefH [zjklee/Handlebars.CSharp](https://github.com/zjklee/Handlebars.CSharp) is going to be deprecated as all of the changes are going to be merged to Handlebars.Net.

@sferencik 
> Or even as soon as the returning helpers (your current PR) are released

I would like to wait for one more PR to be merged before publishing new package (even prerelease one) as it's going to include some important changes.

**Comment by StefH** [comment]
@zjklee OK. I did not know that. Are you taking over this project ? Or merging all your changes from Handlebars.CSharp into this project ?

**Comment by zjklee** [comment]
@StefH yes, I'm going to be one of the maintainers.

**Comment by sferencik** [comment]
Great news, @zjklee @rexm!

**Comment by StefH** [comment]
OK.

Once you are complete, create an issue in https://github.com/StefH/Handlebars.Net.Helpers project so I can take action to upgrade.
