### ISSUE TITLE
[Question] How can I load templates from files

### ISSUE THREAD

**Issue by dawoe** [Handlebars-Net/Handlebars.Net#370]
Hi,
How can i load handlebar templates from files ? All the examples in the readme use inline declared templates.

Dave

**Comment by zjklee** [comment]
Hello @dawoe.
You can use the following `Compile` override and passing `StreamReader` as an argument:
```csharp
Action<TextWriter, object> Compile(TextReader template)
```

Example:
```csharp
[Fact]
public void FromFileExample()
{
    using var fileStream = File.OpenRead(""); 
    using var source = new StreamReader(fileStream);
    var handlebars = Handlebars.Create();
    var template = handlebars.Compile(source);
    var data = new
    {
        name = "Handlebars.Net"
    };
    
    using var writer = new StringWriter();
    template(writer, data);
    Assert.Equal("Hello, Handlebars.Net!", writer.ToString());
}
```

Please provide more details on your use case if you need more support on you question.

**Comment by dawoe** [comment]
I was looking at the CompileView method. But it seems I need to implement a ViewFileSystem for that.

Looking at the tests myself now to see how that is done.

Dave
