### ISSUE TITLE
[Question] Do not replace if {{identifier}} data is not provided.

### ISSUE THREAD

**Issue by leisenstein** [Handlebars-Net/Handlebars.Net#373]
If you have a template, but the field that should be replaced is not included when template(data) is called, it replaces it with a blank string.  

Is there a way to just skip that field and leave {{identifier}} in the result?

**Comment by rexm** [comment]
[This unit test](https://github.com/Handlebars-Net/Handlebars.Net/blob/323f4e5dd79fdfc38dc719b92eb08d99b5ba7f34/source/Handlebars.Test/BasicIntegrationTests.cs#L78) shows how to customize the output when a field binding can't be resolved:

```c#
handlebars.Configuration.UnresolvedBindingFormatter = "('{0}' is undefined)";
```

`{0}` is the token that represents the name of the binding, but doesn't include any of the surrounding handlebars `{{ }}` syntax so you'd need to add that into your string formatter.

**Comment by zjklee** [comment]
Alternatively you can use [`helperMissing`](https://handlebarsjs.com/guide/hooks.html#helpermissing) feature (see [this unit test](https://github.com/Handlebars-Net/Handlebars.Net/blob/323f4e5dd79fdfc38dc719b92eb08d99b5ba7f34/source/Handlebars.Test/HelperTests.cs#L279) for reference). This would handle both fields and helpers (in case you want to do any kind of post processing that may involve helpers).

**Comment by marocano1** [comment]
I am having the same problem. Handlebars is stripping out all the items in the template that do not have corresponding properties in the data object. I have tried to implement the "helperMissing" solution. Unfortunately, the "arguments" parameter is always empty and it doesn't work.

![Image](https://github.com/user-attachments/assets/f2a78184-2a00-4473-ae2e-31aff595ed6a)
