### ISSUE TITLE
[Question] Rendering Arabic Content

### ISSUE THREAD

**Issue by elkhawajah** [Handlebars-Net/Handlebars.Net#377]
So I am using handlebars to render emails, but also for email subject I also use handlebars to replace tokens.

A case I have is that I have a string like this "some arabic text here {{token}}"

The token is supposed to render a property that store an arabic text, what I get, is that the token arabic text render as :

` &#1601;&#1603;&#1585;&#1577; &#1605;&#1580;&#1583;&#1610;&#1577 `

Not sure why this is happening, anyone has any experience explain what is done wrong ?

**Comment by zjklee** [comment]
Similar issue: Handlebars-Net/Handlebars.Net/issues/276

**Comment by elkhawajah** [comment]
Thanks @zjklee after digging, using` {{{}}}` solved it, which prevents escaping. thanks!
