### ISSUE TITLE
Throws ArgumentException when debugging

### ISSUE THREAD

**Issue by arsu-leo** [Handlebars-Net/Handlebars.Net#379]
As I was able to fix my issue when I was about to submit, I will put it for reference to anyone having this issue.
Read the "Original bug report" section for the original text.
### The real bug
"Enable Just My Code" Option on Debug options makes it unable to debug, most of calls on this lib throws an Argument exception while debugging.

### Bug research info
Somewhere I saw some references about this option (I'm unable to find it anymore), as they said:

> Ensure "Enable Just My Code" is **checked**, 

So I didn't change anything.

Just before submitting this issue I tried to **uncheck** it and it worked out.

### Solution:
To anyone having this issue:
> System.ArgumentException
>   Message=Cannot bind to the target method because its signature is not compatible with that of the delegate type.

**Uncheck** "Enable Just My Code" on Visual Studio -> Debug -> Options

### Describe the bug
I'm unable to use handlebars, trying to run create(), create(withConfig) or just compile a template from the static interface, throws the following exception:

> System.ArgumentException
>   HResult=0x80070057
>   Message=Cannot bind to the target method because its signature is not compatible with that of the delegate type.
>   Source=System.Private.CoreLib
>   StackTrace:
>    at System.Reflection.RuntimeMethodInfo.CreateDelegateInternal(Type delegateType, Object firstArgument, DelegateBindingFlags bindingFlags) in /_ /src/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 598
>    at System.Reflection.RuntimeMethodInfo.CreateDelegate(Type delegateType) in /_ /src/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 563
>    at HandlebarsDotNet.BuiltinHelpers.<GetHelpers>d__6`1.MoveNext()

### Expected behavior:
The expected behaivour is to receive back an IHandlebars when running create() or a proper callback method of type Action<TextWriter, object> when running HandlebarsDotNet.Handlebars.RegisterTemplate

### Test to reproduce
```csharp
[Fact]
public void SimpleTest()
{
    var handlebars1 = Handlebars.Create(); // this throws
    var cfg = new HandlebarsConfiguration();
    var handlebars2 = Handlebars.Create(cfg); // this also throws

    using (StringReader reader = new StringReader(""))
    {
        Action<System.IO.TextWriter, object> fn = Handlebars.Compile(reader); //this also throws
    }
}
```

### Project info
Project type: .Net Core Class library
Platform: Any CPU
Target framework: .Net Core 3.1

### Handlebars info:
Handlebars.Net v1.11.5 taken from NuGet 
Publish date Saturday, October 10, 2020 (10/10/2020)

### Visual studio info:
Microsoft Visual Studio Community 2019
Version 16.7.7
VisualStudio.16.Release/16.7.7+30621.155
Microsoft .NET Framework
Version 4.8.03752

C# Tools   3.7.0-6.20514.1+600c0dadd199296df3ed07dfabdc014563a77f7c
Debugging Tools for Windows   10.0.18346.1000
NuGet Package Manager   5.7.0

### .Net system info:
Cmd Command: dotnet --info
SDK de .NET Core (reflejando cualquier global.json):
 Version:   3.1.403
 Commit:    9e895200cd

Entorno de tiempo de ejecución:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.403\

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

.NET Core SDKs installed:
  2.1.511 [C:\Program Files\dotnet\sdk]
  2.1.512 [C:\Program Files\dotnet\sdk]
  2.1.519 [C:\Program Files\dotnet\sdk]
  3.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### Other system info:
Microsoft Windows 10 Pro (10.0.18363 compilación 18363)
HP ProBook 440 G6, x64
Processor Intel(R) Core(TM) i7-8565U CPU

**Comment by arsu-leo** [comment]
Fixed

**Comment by zjklee** [comment]
Hello @arsu-leo
Thanks for reporting the issue. I have some ideas on a root cause. I assume it's already fixed in master. I'd verify it once new package is published.

**Comment by arsu-leo** [comment]
I didn't realise until later on, but this exceptions are not really breaking through. As visual studio states "Exception User-Unhandled".
This doesn't means that it propagates back to the caller. It's just visual studio telling you "Hey, there is some kind of unexpected exception here", but if I just run the code forward it goes on. So the exception is catched later on. 
This is just a new behaviour on Visual Studio a lot of us are not used to. I did see this exceptions on other libs like the System.Net.Sockets, once you start seeing them usually just disable that type exception on the exceptions settings buttons it appears on the exception dialog.
Possibly there is nothing you need to change on the library to keep it running.

**Comment by zjklee** [comment]
OK, thanks for clarification.
