### ISSUE TITLE
MSTest unit tests don't run

### ISSUE THREAD

**Issue by andycnguyen** [Handlebars-Net/Handlebars.Net#393]
### Describe the bug
MSTest unit tests don't run. I've found the following exception noted in my logs:

`An exception occurred while invoking executor 'executor://mstestadapter/v2': Type 'HandlebarsDotNet.Polyfills.AsyncLocal`1+Container[[HandlebarsDotNet.Collections.ImmutableStack`1[[HandlebarsDotNet.Runtime.AmbientContext, Handlebars, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]], Handlebars, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]]' in Assembly 'Handlebars, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.`

**Comment by zjklee** [comment]
Hello @andycnguyen 
Can you please provide more details on your setup? Ideally would be a test project trimmed as much as possible that can be used to reproduce the failure.
