### ISSUE TITLE
Exception: Cannot create ObjectDescriptor for type

### ISSUE THREAD

**Issue by StefH** [Handlebars-Net/Handlebars.Net#399]
Code below used to work for version 1.9.x

``` c#
var handlebars = Handlebars.Create();
handlebars.RegisterHelper("ArrayTest", (writer, context, arguments) =>
{
	var array = new object[]
	{
		1,
		"two"
	};

	writer.WriteSafeString($"[{string.Join(", ", array)}]");
});

var templateX = handlebars.Compile("{{#each (ArrayTest min=6)}}_{{this}}_{{/each}}");
var resultX = templateX.Invoke("");
Console.WriteLine("ArrayTest = " + resultX);
```

What I'm doing wrong?

**Comment by zjklee** [comment]
Hello @StefH 
My first guess is that you're passing a string as an argument to the template.
Can you please provide a stacktrace so I can tell more?

**Comment by StefH** [comment]
```
Unhandled exception. HandlebarsDotNet.HandlebarsRuntimeException: Cannot create ObjectDescriptor for type
   at HandlebarsDotNet.Compiler.Iterator.Iterate(BindingContext context, EncodedTextWriter writer, ChainSegment[] blockParamsVariables, Object target, TemplateDelegate template, TemplateDelegate ifEmpty)
   at lambda_method2(Closure , EncodedTextWriter& , BindingContext )
   at HandlebarsDotNet.HandlebarsEnvironment.<>c__DisplayClass15_0.<Compile>b__0(TextWriter writer, Object context, Object data)
   at HandlebarsDotNet.HandlebarsEnvironment.<>c__DisplayClass16_0.<Compile>b__0(Object context, Object data)
   at ConsoleApp.Program.Main(String[] args) in C:\Users\azurestef\Documents\Github\Handlebars.Net.Helpers\examples\ConsoleApp\Program.cs:line 27
```

**Comment by zjklee** [comment]
OK, I see.
The problem is that you're trying to iterate over a `string` (result of `ArrayTest` helper) which is not supported (see [jsfiddle](http://jsfiddle.net/5aoknu01/5/))
 
The following should work in case you want to iterate over array:
```csharp
var handlebars = Handlebars.Create();
handlebars.RegisterHelper("ArrayTest", (context, arguments) =>
{
    return new object[] { 1, "two" };
});

var templateX = handlebars.Compile("{{#each (ArrayTest min=6)}}_{{this}}_{{/each}}");
var resultX = templateX.Invoke(null);
Console.WriteLine("ArrayTest = " + resultX);
```

**Comment by StefH** [comment]
Sounds logic.
However, this used to work in previous version.

`"{{[String.Join] [\"a\",\"b\",\"c\"] ':'}}"` that also fails, probably same reason?

Exception here is:
`
  Message: 
    System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace: 
    PathResolver.ResolveValue(Boolean isVariable, BindingContext context, Object instance, ChainSegment chainSegment)
    PathResolver.ResolvePath(BindingContext context, PathInfo pathInfo)
    lambda_method(Closure , EncodedTextWriter& , BindingContext )
    <>c__DisplayClass15_0.<Compile>b__0(TextWriter writer, Object context, Object data)
    <>c__DisplayClass16_0.<Compile>b__0(Object context, Object data)
    StringHelpersTemplateTests.Join(String template, String expected) line 60
`

**Comment by StefH** [comment]
I think that when a string starts with `[` : the new Handlebars.net code thinks this is always an array.

**Comment by zjklee** [comment]
Handlebars does not know anything about arrays on a template level, meaning in Handlebars `[]` is not an array declaration. `[\"a\",\"b\",\"c\"]` is wrong parameter in this context - it treats it as `\"a\",\"b\",\"c\"` [literal](https://handlebarsjs.com/guide/expressions.html#literal-segments) and would try to resolve from context. If you want to treat it as a string-encoded JSON array you should do it like this: `'[\"a\",\"b\",\"c\"]'`

**Comment by zjklee** [comment]
@StefH btw, I've tried to reproduce `System.NullReferenceException` with something similar to what you did and was not able to. Most probably there's something weird on your end.

**Comment by StefH** [comment]
In the previous version, this worked:
``` c#
"{{[String.Join] [\"a\",\"b\",\"c\"] ':'}}"
```
(The **String.Join** is a helper which is registered correctly)

When this code was invoked, the arguments looked like this:
![image](https://user-images.githubusercontent.com/249938/101601891-807b3780-39fd-11eb-9df8-0fb8d899ec30.png)

And because the `[\"a\",\"b\",\"c\"]` was treated as a `UndefinedBindingResult`, I could just try to convert that string into a real array using NewtonsoftJson which creates a real array which can be passed to the String.Join helper.

Now the new code just throws exception:
`
  Message: 
    System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace: 
    PathResolver.ResolveValue(Boolean isVariable, BindingContext context, Object instance, ChainSegment chainSegment)
    PathResolver.ResolvePath(BindingContext context, PathInfo pathInfo)
    lambda_method(Closure , EncodedTextWriter& , BindingContext )
    <>c__DisplayClass15_0.<Compile>b__0(TextWriter writer, Object context, Object data)
    <>c__DisplayClass16_0.<Compile>b__0(Object context, Object data)
    StringHelpersTemplateTests.Join(String template, String expected) line 60
`

**Comment by StefH** [comment]
Update...

It seems that the origin from the error is different.

Previously I could use code like:
``` c#
// Arrange
var action = _handlebarsContext.Compile(template);

// Act
var result = action("");
```

But now I have to use:
``` c#
// Arrange
var action = _handlebarsContext.Compile(template);

// Act
var result = action(null); // null instead of "" ?
```

**Comment by zjklee** [comment]
Looks like I'd need a closer look at passing string as template context. Thanks for isolating the problem.

**Comment by StefH** [comment]
b.t.w. calling `action(123);` does also seem to work fine

**Comment by zjklee** [comment]
I've already found a problem with `NullReferenceException` and fix will be pushed soon.
