### ISSUE TITLE
Any porting available for .net core 5.0

### ISSUE THREAD

**Issue by Nagendracv** [Handlebars-Net/Handlebars.Net#415]
Looking forward to  .net core support for this library

**Comment by zjklee** [comment]
Hello @Nagendracv 
Library supports netstandard 2.0 and 2.1 so you should be able to use it with net5 without any problems.
PR with net5 target is welcome 😀

**Comment by huysentruitw** [comment]
I'm using this successfully in a .NET 5 project, so not sure what the question here is referring to. Can you elaborate?

**Comment by jonfast565** [comment]
Can also use with .NET 5.
