### ISSUE TITLE
[Question] How to escape {{ }} ?

### ISSUE THREAD

**Issue by StefH** [Handlebars-Net/Handlebars.Net#419]
I've this expression:
``` c#
"{{Format {{Now}} \"yyyy-MM-dd\"}}",
```

Where `{{Now}}` is a helper which returns the current datetime.
And `Format` is an helper which formats the DateTime as the specified format.

However, this fails:
```
Unhandled exception. HandlebarsDotNet.HandlebarsParserException: Reached unparseable token in expression: {Now}} "yyyy-MM-dd"}}
```

So my question is how to properly escape the {{ for the Now?

**Comment by zjklee** [comment]
Hello @StefH 

Correct expression would look like this: 
```handlebars
"{{Format (Now) 'yyyy-MM-dd'}}"
```

**Comment by StefH** [comment]
Thanks !
