### ISSUE TITLE
[Question] Double quotes are automatically escaped?

### ISSUE THREAD

**Issue by StefH** [Handlebars-Net/Handlebars.Net#420]
When I've a helper which returns a `"`, this is converted to `&quot;` when using the template(...) method?

**Comment by zjklee** [comment]
It depends on the helper. Posting an example of what you're doing and what is confusing can help answering your question.

**Comment by StefH** [comment]
I used this helper:
``` c#
handlebarsContext.RegisterHelper(helperName, (context, arguments) =>
            {
                return "\"";
            });
```

However I discovered that I cannot use this one but another one:
``` c#
handlebarsContext.RegisterHelper(helperName, (writer, context, arguments) =>
{
   writer.WriteSafeString("\"");
});
```
