### ISSUE TITLE
`Dictionary<string, object>` or `dynamic` model is not supported by layout views

### ISSUE THREAD

**Issue by heemskerkerik** [Handlebars-Net/Handlebars.Net#440]
### Describe the bug
When the `context` parameter contains a model of type `Dictionary<string, object>` or `dynamic`, expressions in a layout view cannot be bound to it.

This seems to be because the way context is passed to layout views is by wrapping the output of the ‘main’ view and the original context into a `DynamicViewModel`. Unfortunately, `DynamicViewModel` only supports reflection member access.

This conflicts with the guidance in the documentation that, for the best performance, models should be dictionaries.

### Expected behavior:
When the value of the `context` parameter of a view is a `Dictionary<string, object>` or a `dynamic`, I expect that expressions in the layout view are able to resolve values as they do in regular views.

In more detail: I expect that `DynamicViewModel` is capable of handling regular dictionaries and dynamic values, as well as POCOs.

### Test to reproduce
```csharp
[Fact]
public void CanUseDictionaryModelInLayout()
{
    var files = new FakeFileSystem()
                {
                    { "views\\layout.hbs", "Layout: {{property}}\r\n{{{body}}}" },
                    { "views\\someview.hbs", "{{!< layout}}\r\n\r\nBody: {{property}}" },
                };

    var handlebarsConfiguration = new HandlebarsConfiguration() { FileSystem = files };
    var handlebars = Handlebars.Create(handlebarsConfiguration);
    var render = handlebars.CompileView("views\\someview.hbs");
    var output = render(
        new Dictionary<string, object>
        {
            { "property", "Foo" },
        }
    );

    Assert.Equal("Layout: Foo\r\n\r\nBody: Foo", output);
    // actual value is "Layout: \r\n\r\nBody: Foo"
}

[Fact]
public void CanUseDynamicModelInLayout()
{
    var files = new FakeFileSystem()
                {
                    { "views\\layout.hbs", "Layout: {{property}}\r\n{{{body}}}" },
                    { "views\\someview.hbs", "{{!< layout}}\r\n\r\nBody: {{property}}" },
                };

    dynamic model = new MyDynamicModel();
    var handlebarsConfiguration = new HandlebarsConfiguration() { FileSystem = files };
    var handlebars = Handlebars.Create(handlebarsConfiguration);
    var render = handlebars.CompileView("views\\someview.hbs");
    var output = render(
        model
    );

    Assert.Equal("Layout: Foo\r\n\r\nBody: Foo", output);
    // actual value is "Layout: \r\n\r\nBody: Foo"
}

private class MyDynamicModel: DynamicObject
{
    private readonly Dictionary<string, object> _properties =
        new Dictionary<string, object>
        {
            { "property", "Foo" },
        };

    public override IEnumerable<string> GetDynamicMemberNames() => _properties.Keys;
    public override bool TryGetMember(GetMemberBinder binder, out object result) =>
        _properties.TryGetValue(binder.Name, out result);
}
```

**Comment by zjklee** [comment]
Related to https://github.com/Handlebars-Net/Handlebars.Net/issues/97 as might be obsolete if view engine redesign comes first.

**Comment by heemskerkerik** [comment]
I don't think this would be very difficult to fix in the current implementation of `DynamicViewModel`. If you don't mind, I'd like to give it a go and create a PR for that. Not sure if #439 is as easy to fix.

**Comment by zjklee** [comment]
@heemskerkerik , sure, go ahead with PR 👍

**Comment by zjklee** [comment]
@heemskerkerik regarding fix implementation.
Consider replacing `DynamicViewModel` implementation with something that would not include inheritance from `DynamicObject`. Below you'd be able to find some of my drafts (it's not tested well) which you can use as an inspiration.

```csharp
public sealed class DynamicViewModel
{
    private readonly object[] _objects;

    public DynamicViewModel(params object[] objects) => _objects = objects;

    private bool TryGetValue(
        ICompiledHandlebarsConfiguration configuration,
        ChainSegment property,
        out object value)
    {
        for (var index = 0; index < _objects.Length; index++)
        {
            var target = _objects[index];
            if (!ObjectDescriptor.TryCreate(target, configuration, out var descriptor))
            {
                value = null;
                return false;
            }

            if (descriptor.MemberAccessor.TryGetValue(target, property, out value))
            {
                return true;
            }
        }

        value = null;
        return false;
    }
    
    internal class Descriptor : IObjectDescriptorProvider
    {
        private static readonly Type Type = typeof(DynamicViewModel);

        private readonly ObjectDescriptor _objectDescriptor;

        public Descriptor(ICompiledHandlebarsConfiguration configuration)
        {
            _objectDescriptor = new ObjectDescriptor(
                Type,
                new MemberAccessor(configuration),
                (descriptor, o) =>
                {
                    var vm = (DynamicViewModel) o;

                    return Enumerate(vm._objects, (ICompiledHandlebarsConfiguration) descriptor.Dependencies[0]);

                    static IEnumerable<object> Enumerate(object[] objects, ICompiledHandlebarsConfiguration configuration)
                    {
                        for (var index = 0; index < objects.Length; index++)
                        {
                            var from = objects[index];
                            var objectDescriptor = ObjectDescriptor.Create(@from, configuration);
                            var properties = objectDescriptor.GetProperties(objectDescriptor, @from);
                            foreach (var property in properties)
                            {
                                yield return property;
                            }
                        }
                    }
                }, dependencies: configuration
            );
        }
        
        public bool TryGetDescriptor(Type type, out ObjectDescriptor value)
        {
            if (type != Type)
            {
                value = ObjectDescriptor.Empty;
                return false;
            }
            
            value = _objectDescriptor;
            return true;
        }
    }
    
    internal class MemberAccessor : IMemberAccessor
    {
        private readonly ICompiledHandlebarsConfiguration _configuration;

        public MemberAccessor(ICompiledHandlebarsConfiguration configuration)
        {
            _configuration = configuration;
        }
        
        public bool TryGetValue(object instance, ChainSegment memberName, out object value)
        {
            var vm = (DynamicViewModel) instance;
            return vm.TryGetValue(_configuration, memberName, out value);
        }
    }
}
```

**Comment by heemskerkerik** [comment]
@zjklee I was able to get binding working just fine, but I'm not sure how to implement `IIterator` for `DynamicViewModel`. It's easy enough when all the objects are just POCOs or dictionaries, but this seems to be a valid way to instantiate a `DynamicViewModel`:

```csharp
var vm = new DynamicViewModel(
    new
    {
        foo = "Bar",
    },
    Enumerable.Range(1, 10)
);
```

I don't think iterating over that makes any sense. From that perspective, I could implement an `IIterator` that does nothing, or throws an exception when `ThrowOnUnresolvedBindingExpression` is true.

**Comment by zjklee** [comment]
@heemskerkerik 
This is a good case. However, I do not think that keeping it unimplemented or throwing are good options.

At this point the only usage for `DynamicViewModel` is:
```csharp
var vmContext = new [] {new {body = inner}, context.Value};
var viewModel = new DynamicViewModel(vmContext);
```
Here only `context.Value` has a "real" usage in context of `DynamicViewModel` -  `DynamicViewModel` proxies member access calls to current context value. `new {body = inner}` only provides access to `body` property in `layout` itself.
Based on the above we can consider it as an object that can contain only POCOs. In this case `IIterator` implementation should be straightforward.

Unfortunately `DynamicViewModel` is a public type and we do not know whether it's used by anyone. As a workaround we can declare and use a new `internal` type and leave `DynamicViewModel` as is for now.

**Comment by zjklee** [comment]
@heemskerkerik 
Probably you can ignore my previous comment as we do not really control the value in `context.Value` and it can still be not obvious what to do as part of iterator in case current value would be enumerable.
In this case, yes, throw is a good option.

**Comment by heemskerkerik** [comment]
@zjklee I actually liked the idea of creating a new type, which can be much more focused and less flexible. Like this

```csharp
internal class LayoutViewModel
{
  private readonly string _body;
  private readonly object _value;
}
```

In the member accessor we intercept the `body` property, and forward the rest to the `ObjectDescriptor` for `_value`, and we can do the same for `GetProperties` (where we amend `body`) and for `Iterator` which we just forward altogether.

Let me know what you think.

**Comment by zjklee** [comment]
@heemskerkerik 
Yep, I like your suggestion and looking forward to see your PR 😉
