### ISSUE TITLE
IndexOutOfRangeException in HandlebarsDotNet.PathStructure.PathResolver.ResolvePath for nested object path block expression

### ISSUE THREAD

**Issue by swijnands** [Handlebars-Net/Handlebars.Net#442]
### Describe the bug

Trying to enumerate an array via a nested object path:
```csharp
{{#bundles.styles.vendor}}{{this}}{{/bundles.styles.vendor}}
```

Results in an IndexOutOfRangeException exception.

### Expected behavior:

I would expect the same result as when not using a nested path, i.e. 
```csharp
{{#arr}}....{/arr}}
```
Or, alternatively, if this is not supported: a clearer exception message.

### Test to reproduce
```csharp
var context = new
{
  bundles = new
  {
	  styles = new
	  {
		  vendor = new[] { "a", "b", "c" }
	  }
  },
  arr = new[] { "d", "e", "f"}
};

// Works: Output = "abc"
Handlebars.Compile("{{#each bundles.styles.vendor}}{{this}}{{/each}}")(context).Dump();

// Works: Output = "def"
Handlebars.Compile("{{#arr}}{{this}}{{/arr}}")(context).Dump();

// Fails: IndexOutOfRangeException in HandlebarsDotNet.PathStructure.PathResolver.ResolvePath
// On line #36: if (!TryResolveValue(pathInfo.IsVariable, context, pathChain[0], instance, out instance))
Handlebars.Compile("{{#bundles.styles.vendor}}{{this}}{{/bundles.styles.vendor}}")(context).Dump();```
```

**Comment by zjklee** [comment]
This should definitely be supported. 
Looks like something weird is happening [when we're trying to resolve an actual array to enumerate on](https://github.com/Handlebars-Net/Handlebars.Net/blob/master/source/Handlebars/Helpers/BlockHelpers/MissingBlockHelperDescriptor.cs#L24).

**Comment by sushantduggal** [comment]
Facing the same issue, is there a resolution on this?

**Comment by abraham-fox** [comment]
No updates for 5 month - I assume I can grab this :) and it seems I've found a simple solution for the issue. @zjklee please take a look at #488.
