### ISSUE TITLE
Nested boolean helper function always resolves to false

### ISSUE THREAD

**Issue by gtwilliams03** [Handlebars-Net/Handlebars.Net#445]
### Describe the bug
Nested boolean helper function always resolves to false value.  Works fine if not nested.

### Expected behavior:
Obtain the same value for the helper whether it is nested or not.

### Test to reproduce
```csharp
            Handlebars.RegisterHelper("IsEqual", (writer, options, context, arguments) => {
                if (JsonConvert.SerializeObject((arguments[0] ?? "").ToString(), Formatting.None) == JsonConvert.SerializeObject((arguments[1] ?? "").ToString(), Formatting.None))
                {
                    options.Template(writer, (object)context);
                }
                else
                {
                    options.Inverse(writer, (object)context);
                }
            });
```

### Other related info

Example data:
```
data = {
    Item: { Size: 'Small', Type: 'Test' }
}
```

Sample template to reproduce the error: 

```
<p>Unnested: {{#IsEqual Item.Type "Test"}}Is a Test!{{else}}Is not a test...{{/IsEqual}}</p>
<p>Nested: {{#IsEqual Item.Size "Small"}}Is Small, type: {{#IsEqual Item.Type "Test"}}Is a Test!{{else}}Is not a test...{{/IsEqual}}{{else}}is not small...{{/IsEqual}}</p>
```

Sample output:

```
Unnested: Is a Test!
Nested: Is Small, type: Is not a test...
```

When I logged the output of these values inside the helper function above, e.g.,

```
Console.WriteLine(JsonConvert.SerializeObject(arguments));
```

I think I got some odd results:

```
["Test","Test"] // Expected
["Small","Small"] // Expected
[{"Value":"Item"},"Test"] // Not expected
```
---

**Comment by gtwilliams03** [comment]
My code is running Handlebars-Net 2.0.7.  FWIW, this same code worked on 1.10.0.

**Comment by zjklee** [comment]
Hello @gtwilliams03 
Most probably the problem is in the following code: `(object)context`. Cast to `object` should be removed as `Context` is a special type and is handled differently.

**Comment by gtwilliams03** [comment]
@zjklee Thank you! Removing `(object)` did the trick.  I have no idea where that came from (but the code base was very old so likely a holdover from a much earlier version of `Handlebars.Net`.
