### ISSUE TITLE
Improve performance for large arrays (10.000+)

### ISSUE THREAD

**Issue by albertschulz** [Handlebars-Net/Handlebars.Net#448]
I want to render a large array, with 200.000 elements.
Anyhow, even with the most basic template with an #each loop & only printing the element, performance is really low.

Measurements:
```
Elements | Rendering Time (ms)
  20.000 |          5.500
  40.000 |         20.000
  80.000 |         80.000
```

I would like to know if this behavior is expected. If not, is there room for improvement?

**Comment by albertschulz** [comment]
Here comes a small code example:

```
Stopwatch sw = new Stopwatch();
sw.Start();

var source = "{{#each this}}{{this}}{{/each}}";
var template = Handlebars.Create().Compile(source);
var result = template(Enumerable.Range(0, 20000).ToList());

sw.Stop();
_testOutputHelper.WriteLine("Took: " + sw.ElapsedMilliseconds + " ms");
```

I would like to understand, there the exponential growth origins.

**Comment by albertschulz** [comment]
Hotspots seem to be:
https://github.com/Handlebars-Net/Handlebars.Net/blob/master/source/Handlebars/Collections/LookupSlim.cs#L61
and
https://github.com/Handlebars-Net/Handlebars.Net/blob/master/source/Handlebars/Collections/DictionarySlim.cs#L77

**Comment by zjklee** [comment]
Hello @albertschulz 
Thanks for reporting an interesting case. Unfortunately I'd not be able to have a look myself soon due to personal circumstances but will be happy to assist in your investigation and accept a PR if any.

**Comment by albertschulz** [comment]
Thanks for offering assistance.
The expensive call is actually the calculation of `objectIndex` during iteration:

https://github.com/Handlebars-Net/Handlebars.Net/blob/01ad0e69e56331371f85a1c59c008d7ecfd06f78/source/Handlebars/Iterators/ListIterator'2.cs#L39

Which, in the end, for my case, just returns the same value as `index`.

Changing this line to `var objectIndex = index;` dramatically improves performance, while all tests are still passing.
Whats the impact of this change? In which case would it fail? Is there maybe also a testcase missing, I could add?

**Comment by zjklee** [comment]
Oh I see. Probably the best option is to modify the implementation of `BoxedValue.Int` and limit the number of values cached.

**Comment by albertschulz** [comment]
Could you explain me the purpose of BoxedValue.Int please? Why is it important to cache the indices? Is that basically the functionality for the `index` in `{{#each items index}}`?

**Comment by zjklee** [comment]
The purpose of `BoxedValue.Int` is to reduce the memory allocation caused by boxing of `int` values passed to `@index` by caching and reusing boxed values. The performance penalty for caching values should be neglectable on average-sized workloads assuming template is rendered multiple times (the biggest penalty would be applied the first time template is rendered).

**Comment by albertschulz** [comment]
I created a temporary additional benchmark for this case in my fork:
https://github.com/albertschulz/Handlebars.Net/blob/issues/448/source/Handlebars.Benchmark/LargeArray.cs

Removing the caching extremely improves timing performance.
Anyhow, I don't get any issues with memory usage. I use `dotnet-counters` for measuring heap size.
Even for the `EndToEnd`-Performance test, memory usage is low. Could you give me a hint, for a test with a high memory footprint?

**Comment by albertschulz** [comment]
My change request would be to basically remove caching for the index in all iterators.
I kept a look on the memory profile during the tests, plus the performance test I added, but no negative change.
Would you be okay with that solution?
Was index caching introduced after an issue or precautionary?

**Comment by zjklee** [comment]
It was introduced as a precautionary as part of effort to reduce memory allocations to the minimum number.
My personal preference would be to keep `Boxed.Int` calls but modify the internals of the function so it returns precalculated values for the first 10 (or more) values like it is now but fallback to boxing if value is out of the precalculated range instead of caching.

**Comment by albertschulz** [comment]
Here you go :)
https://github.com/Handlebars-Net/Handlebars.Net/pull/451
