### ISSUE TITLE
HandlebarsDotNet.Handlebars.Configuration.NoEscape Applied Inconsistently

### ISSUE THREAD

**Issue by tonysneed** [Handlebars-Net/Handlebars.Net#468]
### Describe the bug
When iterating over an array using `#each`, the value of `Configuration.NoEscape` reverts to `false`.

### Expected behavior:
`Configuration.NoEscape` remains `true` when set to `true`.

### Test to reproduce
See PR [180](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/pull/180) in my repo.

**Comment by zjklee** [comment]
Hello @tonysneed 
Can you please include the minimal test to the issue here to simplify investigation?

**Comment by tonysneed** [comment]
Here is a [repo](https://github.com/tonysneed/handlebars-encoding-test) with minimal tests that reproduce the issue.

**Comment by tonysneed** [comment]
@zjklee Have you been able to look at the repo with minimal tests that I provided?

**Comment by zjklee** [comment]
Hello @tonysneed 
Unfortunately, I had no spare time to take a look. I'd try to take a look in a next couple of days but I cannot promise when it would happen.
I'd be happy to help you with investigation if you decide to take a deeper look on your own.
