### ISSUE TITLE
Handlebars.Configuration.MissingPartialTemplateHandler is not invoked for partial blocks

### ISSUE THREAD

**Issue by agross** [Handlebars-Net/Handlebars.Net#475]
### Describe the bug

I believe this should throw but it doesn't:

```cs
using HandlebarsDotNet;

class MissingPartial : IMissingPartialTemplateHandler
{
  public void Handle(ICompiledHandlebarsConfiguration configuration, string partialName, in EncodedTextWriter textWriter)
  {
    throw new NotImplementedException();
  }
}

Handlebars.Configuration.MissingPartialTemplateHandler = new MissingPartial();

var tmpl = Handlebars.Compile("{{#>foo}}\ndoesn’t-matter\n{{/foo}}");
tmpl(new object());
```

### Expected behavior:

In the example above, a `NotImplementedException` should be thrown, i.e. `MissingPartialTemplateHandler` should be called because `RegisterTemplate("foo", ...)` has never been called.

**Comment by zjklee** [comment]
Hello @agross 
In your example it would not throw because you use [partial-block](https://handlebarsjs.com/guide/partials.html#partial-blocks): `IMissingPartialTemplateHandler` is not invoked and fallback is rendered instead.

**Comment by agross** [comment]
Ok, thanks the the explanation. 11 days ago I was a Handlebars noob 😉 The issue can be closed.
