### ISSUE TITLE
Supporting `@last` for object iteration by default

### ISSUE THREAD

**Issue by yoshigev** [Handlebars-Net/Handlebars.Net#480]
For JS implementation, `@last` is supported for object iteration since 2014 (added [here](https://github.com/handlebars-lang/handlebars.js/commit/3a9440f954092558275cd4c05a35ba34bcbfa210)).

For .NET it is disabled by default, and controlled by the `SupportLastInObjectIterations` configuration flag, with the following note:

> If `true` enables support for `@last` in object properties iterations. Not supported in Handlebarsjs.

By leaving the default `false`, the .NET engine is incompatible to the JS engine out-of-the-box.

So please consider changing the default to `true`, or at least add documentation of `SupportLastInObjectIterations`...

Thanks,
Yehoshua

**Comment by zjklee** [comment]
I'd be happy to merge the PR 😃
