### ISSUE TITLE
[Question]  upgrade Handlebars.Net from 2.0.10 to 2.1.0, HandlebarsHelpers.Register does not work

### ISSUE THREAD

**Issue by ul-develop** [Handlebars-Net/Handlebars.Net#492]
After upgrade Handlebars.Net from 2.0.10 to 2.1.0, `HandlebarsHelpers.Register` does not work.
Handlebars.Net.Helpers version 2.2.1.

```c#
var handlebars = Handlebars.Create();
HandlebarsHelpers.Register(handlebars);
```
Exception

`
System.MissingMethodException: 'Method not found: 'Void HandlebarsDotNet.IHandlebars.RegisterHelper(System.String, HandlebarsDotNet.HandlebarsReturnHelper)'.'
`

**Comment by zjklee** [comment]
Hello @ul-develop 
2.1.0 has breaking challenges on the binary level. New Helpers package should be released. @StefH, can you please release an update?

**Comment by StefH** [comment]
@ul-develop 
The NuGet for Handlebars.Net.Helpers has been updated to version 2.3.0 to be compatible with Handlebars.Net 2.1.0

**Comment by ul-develop** [comment]
Thank you @StefH @zjklee, The new version of Handlebars.Net.Helpers works well with Handlebars.Net 2.1.0.
