### ISSUE TITLE
Conditional Block Helper Doesn't Work on Dynamic Object from Deserialized String

### ISSUE THREAD

**Issue by jorjen** [Handlebars-Net/Handlebars.Net#501]
### Describe the bug
I'm using the built-in #if conditional block helper. If the context data used is from an explicitly created dynamic object, it works fine. But if the dynamic object is created from a deserialized json string, it doesn't.

### Expected behavior:
Should work with dynamic objects from deserialized json.

### Test to reproduce
```csharp
[Fact]
public void Is_Working()
{
    var handlebars = Handlebars.Create();
    var source = @"{{#if showInput}}{{input}}{{/if}}";
    var render = handlebars.Compile(source );
    var data = new { input = 42, showInput = true };
    
    var actual = render(data);
    Assert.Equal(42, actual);
}

[Fact]
public void Should_Work()
{
    var handlebars = Handlebars.Create();
    var source = @"{{#if showInput}}{{input}}{{/if}}";
    var render = handlebars.Compile(source);
    var context = @"{""input"":""42"",""showInput"":true}";
    var data = System.Text.Json.JsonSerializer.Deserialize<object>(context);
    
    var actual = render(data);
    Assert.Equal(42, actual);
}
```

**Comment by zjklee** [comment]
Hello @jorjen ,
The problem is related to the fact that be default Handlebars has no idea about System.Text.Json. You need to use [Handlebars.Net.Extension.Json](https://github.com/Handlebars-Net/Handlebars.Net.Extension.Json) to make it work:

```csharp
[Fact]
public void Should_Work()
{
    var configuration = new HandlebarsConfiguration();
    configuration.UseJson();
    
    var handlebars = Handlebars.Create(configuration);
    var source = @"{{#if showInput}}{{input}}{{/if}}";
    var render = handlebars.Compile(source);
    var context = @"{""input"":""42"",""showInput"":true}";
    var data = System.Text.Json.JsonSerializer.Deserialize<object>(context);

    var actual = render(data);
    Assert.Equal("42", actual);
}
```

**Comment by jorjen** [comment]
Hi @zjklee ,

Thank you for responding. What version are you using for Handlebars.Net?
I don't see the UseJson() method on the latest version (2.1.0), which I'm currently using. Does this mean that the said method won't be supported in the future anymore?

[https://github.com/Handlebars-Net/Handlebars.Net/blob/master/source/Handlebars/Configuration/HandlebarsConfiguration.cs](https://github.com/Handlebars-Net/Handlebars.Net/blob/master/source/Handlebars/Configuration/HandlebarsConfiguration.cs)

**Comment by zjklee** [comment]
@jorjen 
You need to install extension package. Follow the link in my previous comment for more details.

**Comment by jorjen** [comment]
@zjklee 
Thank you!
