### ISSUE TITLE
Adding links to related libraries in the main readme?

### ISSUE THREAD

**Issue by StefH** [Handlebars-Net/Handlebars.Net#508]
Would it be useful to add links to Handlebars.Net.Extension.Json, Handlebars.Net.Extension.NewtonsoftJson and Handlebars.Net.Helpers on this readme.md , so that the existence from these projects is presented?

**Comment by zjklee** [comment]
Hello @StefH ,
It may be a good idea. I was not thinking of this at those packages are already a part of the Organization.
Would you be able to update the README.md?

**Comment by StefH** [comment]
@zjklee 
I'll do this.

BTW: it seems that you are still using VS2017 to develop this solution?
Because when I open it in vs2019/vs2022 the .sln file is updated;
![image](https://user-images.githubusercontent.com/249938/157416348-38d256b1-c3d1-40d9-a0da-95454ee7aee4.png)


What is your preferred VS version?

**Comment by StefH** [comment]
https://github.com/Handlebars-Net/Handlebars.Net/pull/509
