### ISSUE TITLE
[Question] context param can be modified?

### ISSUE THREAD

**Issue by JuanOrjuelaA** [Handlebars-Net/Handlebars.Net#511]
Hello guys

Is there a way to modify the info from the context param?
I have a list in the context, and I want to remove some items from that list to be displayed in my template.

**Comment by zjklee** [comment]
Hello @JuanOrjuelaA 
You can access context value inside the helper using `context.Value`. You'd still need to cast it to a correct type though.

**Comment by JuanOrjuelaA** [comment]
Awesome, thanks!
