### ISSUE TITLE
[Question] Is there a way to ensure emoji's are properly handled?

### ISSUE THREAD

**Issue by plamber** [Handlebars-Net/Handlebars.Net#528]
Hi,
First of all. Thank you, a lot, for the work done so far. We are using the latest version of HandlebarsDotNet.

We are trying to convert a template with parameters containing an emoji. Find below a code snippet.
```
var template = "Put here some text and '{{title}}'";
var params = new { title = "😆Smile has issues" };
var render = Handlebars.Compile(template);
var subject = render(parameters);
```

The result will be 
```
"Put here some text and '&#55357;&#56838;Smile has issues'";
```

Is there a way to keep the same output even with emojis?

Thank you for your feedback,
Patrick

**Comment by zjklee** [comment]
Hello @plamber . You see this behavior because of default encoding. In order to preserver emojis you'd need to implement your own encoder or disable it all together.

**Comment by zjklee** [comment]
@plamber 

You should have a look at [`ITextEncoder`](https://github.com/Handlebars-Net/Handlebars.Net/blob/master/source/Handlebars/IO/ITextEncoder.cs) and [`HtmlEncoder`](https://github.com/Handlebars-Net/Handlebars.Net/blob/master/source/Handlebars/IO/HtmlEncoder.cs) as its implementation.

**Comment by plamber** [comment]
Thank you. I will have a look into that.
