### ISSUE TITLE
Adding license tag to nuspec file

### ISSUE THREAD

**Issue by ppankiewicz** [Handlebars-Net/Handlebars.Net#553]
Hi,

It is possible to add license tag to nuspec file and regenerate new nuget package?

Currently nuget package contains license information in LICENSE file but there is no information about license in nuspec file. This could be a problem in organizations where such a nuget packages will be blocked to download by proxy because lack of license information from nuget server.

**Comment by StefH** [comment]
https://github.com/Handlebars-Net/Handlebars.Net/pull/564
