### ISSUE TITLE
Value of Dictionary<object, object> doesn't resolve unless keys are all lower case

### ISSUE THREAD

**Issue by alexwiese** [Handlebars-Net/Handlebars.Net#563]
### Describe the bug

Example:

Handlebars.Net 2.1.4

Given a `Dictionary<object, object>` only keys that are lower case are resolved:
![image](https://github.com/Handlebars-Net/Handlebars.Net/assets/2103355/fb5a8e59-ea2f-4d8f-ad5c-185899d4f63f)

### Expected behavior:
The values can be resolved using keys that contain upper case letters.

### Test to reproduce
```csharp
var input = new Dictionary<object, object> 
{
	["foo"] = "123",
	["FooBar"] = "456",
	["barFoo"] = "789"
};

var template = """
- {Foo} => {{Foo}}
- {foo} => {{foo}}
- {fooBar} => {{fooBar}}
- {FooBar} => {{FooBar}}
- {barFoo} => {{barFoo}}
""";

Handlebars.Compile(template)(input);
```

### Other related info
Looks like it's related to [this code](https://github.com/Handlebars-Net/Handlebars.Net/blob/50614fd844e5360eb10e76154aa74da4d7bf12ce/source/Handlebars/MemberAccessors/DictionaryMemberAccessor.cs#L15) which always uses `memberName.LowerInvariant`.
Is there a reason it's always converted to lower case before accessing the value?
Is a special case needed for `Dictionary<object, TValue>` to handle this?

**Comment by leong985664** [comment]
@oformaniuk This one still appears to be a bug to me. It doesn't resolve for keys that are capitalized.
